
package view;

import controller.AkademisyenYonetici;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
public class NewJFrame extends javax.swing.JFrame {

    private AkademisyenYonetici ay;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        ay=new AkademisyenYonetici(akademisyenTablos);
        ay.ac();
     
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kayiteklemeDialog = new javax.swing.JDialog();
        kaydetEkleButton = new javax.swing.JButton();
        kaydetIDGiris = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kaydetSicilNoGiris = new javax.swing.JTextField();
        kaydetSehirGiris = new javax.swing.JTextField();
        kaydetTelGiris = new javax.swing.JTextField();
        kaydetAdSoyadGiris = new javax.swing.JTextField();
        guncelleDialog = new javax.swing.JDialog();
        guncelleIDNo = new javax.swing.JTextField();
        guncelleAdSoyad = new javax.swing.JTextField();
        guncelleSicilNo = new javax.swing.JTextField();
        guncelleSehir = new javax.swing.JTextField();
        guncelleTel = new javax.swing.JTextField();
        guncelleSaveButton = new javax.swing.JButton();
        listeleButton = new javax.swing.JButton();
        arananSehirGiris = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        akademisyenTablos = new javax.swing.JTable();
        bulButton = new javax.swing.JButton();
        yeniKayitButton = new javax.swing.JButton();
        silButton = new javax.swing.JButton();
        guncelleButton = new javax.swing.JButton();

        kayiteklemeDialog.setMinimumSize(new java.awt.Dimension(350, 380));

        kaydetEkleButton.setText("Ekle");
        kaydetEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetEkleButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Sicil No");

        jLabel3.setText("Ad Soyad");

        jLabel4.setText("Sehir");

        jLabel5.setText("Tel");

        javax.swing.GroupLayout kayiteklemeDialogLayout = new javax.swing.GroupLayout(kayiteklemeDialog.getContentPane());
        kayiteklemeDialog.getContentPane().setLayout(kayiteklemeDialogLayout);
        kayiteklemeDialogLayout.setHorizontalGroup(
            kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayiteklemeDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kaydetEkleButton)
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayiteklemeDialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kayiteklemeDialogLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaydetTelGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayiteklemeDialogLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaydetSehirGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kayiteklemeDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaydetIDGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayiteklemeDialogLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaydetSicilNoGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayiteklemeDialogLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kaydetAdSoyadGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        kayiteklemeDialogLayout.setVerticalGroup(
            kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayiteklemeDialogLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kaydetIDGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kaydetSicilNoGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kaydetAdSoyadGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kaydetSehirGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kayiteklemeDialogLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(kayiteklemeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(kaydetTelGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kayiteklemeDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 96, Short.MAX_VALUE)
                        .addComponent(kaydetEkleButton)
                        .addGap(30, 30, 30))))
        );

        guncelleDialog.setMinimumSize(new java.awt.Dimension(400, 400));

        guncelleSaveButton.setText("Güncelle");
        guncelleSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guncelleDialogLayout = new javax.swing.GroupLayout(guncelleDialog.getContentPane());
        guncelleDialog.getContentPane().setLayout(guncelleDialogLayout);
        guncelleDialogLayout.setHorizontalGroup(
            guncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guncelleDialogLayout.createSequentialGroup()
                .addGroup(guncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guncelleDialogLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(guncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guncelleTel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelleSehir, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelleSicilNo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelleAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelleIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(guncelleDialogLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(guncelleSaveButton)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        guncelleDialogLayout.setVerticalGroup(
            guncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guncelleDialogLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(guncelleIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(guncelleSicilNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(guncelleAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(guncelleSehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guncelleTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guncelleSaveButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listeleButton.setText("Listele");
        listeleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeleButtonActionPerformed(evt);
            }
        });

        akademisyenTablos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(akademisyenTablos);

        bulButton.setText("Bul");
        bulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulButtonActionPerformed(evt);
            }
        });

        yeniKayitButton.setText("Yeni kayıt");
        yeniKayitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniKayitButtonActionPerformed(evt);
            }
        });

        silButton.setText("Sil");
        silButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButtonActionPerformed(evt);
            }
        });

        guncelleButton.setText("Güncelle");
        guncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arananSehirGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bulButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(listeleButton)
                            .addGap(18, 18, 18)
                            .addComponent(yeniKayitButton)
                            .addGap(28, 28, 28)
                            .addComponent(silButton)
                            .addGap(40, 40, 40)
                            .addComponent(guncelleButton))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arananSehirGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulButton))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeleButton)
                    .addComponent(yeniKayitButton)
                    .addComponent(silButton)
                    .addComponent(guncelleButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listeleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeleButtonActionPerformed
       
      ay.getir();
            
       
    }//GEN-LAST:event_listeleButtonActionPerformed

    private void bulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulButtonActionPerformed
        if (!arananSehirGiris.getText().trim().equals("")) {
            ay.akademisyenleriGetir(arananSehirGiris.getText().trim(), "sehir");
        }
           
    }//GEN-LAST:event_bulButtonActionPerformed

    private void yeniKayitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniKayitButtonActionPerformed
        kayiteklemeDialog.setVisible(true);
    }//GEN-LAST:event_yeniKayitButtonActionPerformed

    private void kaydetEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetEkleButtonActionPerformed
      int a=JOptionPane.showConfirmDialog(this,"Kayıt eklendi","Bilgi",JOptionPane.DEFAULT_OPTION);   
      if(a==0)
      { int id=Integer.valueOf(kaydetIDGiris.getText());
       String sicilNo=kaydetSicilNoGiris.getText();
       String adSoyad=kaydetAdSoyadGiris.getText();
       String sehir=kaydetSehirGiris.getText();
       String tel=kaydetTelGiris.getText();
        ay.yeniKayitEkle(id,sicilNo,adSoyad,sehir,tel);
         kayiteklemeDialog.setVisible(false);
      }
       
       
      
       
       
       
           
    }//GEN-LAST:event_kaydetEkleButtonActionPerformed

    private void silButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButtonActionPerformed
      int a=akademisyenTablos.getSelectedRow();
     ay.kayitSil(a);
     JOptionPane.showConfirmDialog(this,"Kayıt Silindi...","Bilgi",JOptionPane.DEFAULT_OPTION);   
      
    }//GEN-LAST:event_silButtonActionPerformed

    private void guncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleButtonActionPerformed
          
        int a=akademisyenTablos.getSelectedRow();
        guncelleDialog.setVisible(true);
        ArrayList bilgilerListe=ay.bilgileriAl(a); //güncelleye bastığımda seçtiğim tablo row sırasındaki bilgilerin
                                                   //güncelleme ekranındaki edittextlerde gözükmesi için...
        
        guncelleIDNo.setText(bilgilerListe.get(0).toString());
        guncelleSicilNo.setText(bilgilerListe.get(1).toString());
        guncelleAdSoyad.setText(bilgilerListe.get(2).toString());
        guncelleSehir.setText(bilgilerListe.get(3).toString());
        guncelleTel.setText(bilgilerListe.get(4).toString());
        
      
        
    }//GEN-LAST:event_guncelleButtonActionPerformed

    private void guncelleSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleSaveButtonActionPerformed
     
        int secilenRow=akademisyenTablos.getSelectedRow();
        
      ay.guncelle(guncelleIDNo.getText(),guncelleSicilNo.getText(),guncelleAdSoyad.getText(),guncelleSehir.getText(),guncelleTel.getText(),secilenRow);
     int a=JOptionPane.showConfirmDialog(this,"Seçtiğiniz kayıt güncellendi.","Bilgi",JOptionPane.DEFAULT_OPTION);
    if(a==0)
    {
        guncelleDialog.setVisible(false);
    }
   
      
    }//GEN-LAST:event_guncelleSaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable akademisyenTablos;
    private javax.swing.JTextField arananSehirGiris;
    private javax.swing.JButton bulButton;
    private javax.swing.JTextField guncelleAdSoyad;
    private javax.swing.JButton guncelleButton;
    private javax.swing.JDialog guncelleDialog;
    private javax.swing.JTextField guncelleIDNo;
    private javax.swing.JButton guncelleSaveButton;
    private javax.swing.JTextField guncelleSehir;
    private javax.swing.JTextField guncelleSicilNo;
    private javax.swing.JTextField guncelleTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kaydetAdSoyadGiris;
    private javax.swing.JButton kaydetEkleButton;
    private javax.swing.JTextField kaydetIDGiris;
    private javax.swing.JTextField kaydetSehirGiris;
    private javax.swing.JTextField kaydetSicilNoGiris;
    private javax.swing.JTextField kaydetTelGiris;
    private javax.swing.JDialog kayiteklemeDialog;
    private javax.swing.JButton listeleButton;
    private javax.swing.JButton silButton;
    private javax.swing.JButton yeniKayitButton;
    // End of variables declaration//GEN-END:variables
}
